services:
    aerospikedb:
        image: aerospike/aerospike-server:latest
        networks:
        - aerospikenetwork
        deploy:
            replicas: 2
            endpoint_mode: dnsrr
        labels:
            com.aerospike.cluster: "MYPROJECT"
        command: [ "--config-file","/run/secrets/aerospike.conf"]
        secrets:
        - source: conffile
          target: aerospike.conf
          mode: 0440

    meshworker:
        image: aerospike/aerospike-tools:latest
        networks:
        - aerospikenetwork
        depends_on:
        - aerospikedb
        volumes:
          - ./discovery.py:/run/secrets/discovery.py
        entrypoint:
          - "/run/secrets/discovery --servicename aerospikedb -i 5 -v"
        secrets:
        - source: discoveryfile
          target: discovery
          mode: 0750

networks:
    aerospikenetwork:
        driver: overlay
        attachable: true

secrets:
    conffile:
        file: ./aerospike.conf
    discoveryfile:
        file: ./discovery.py